Repository JulianFrattini/cira, pull requests merged in 2023-10, with the labels that each got.

#69 Add env create command to README
  README.md
Labels: documentation

#71 Patch handling of brackets
  src/converters/sentencetolabels/labelingconverter.py
  static/sentences/sentence-18.json
  test/converters/graphtotestsuite/test_testsuiteconverter.py
  test/converters/labelstograph/test_graphconverter.py
  test/converters/sentencetolabels/test_labeler.py
Labels: bug

#72 Refactor EventResolver to use consts
  src/converters/labelstograph/eventresolver.py
  src/util/constants.py
Labels: enhancement

#73 Refactor eventconnector to use consts and improve readability
  src/converters/labelstograph/eventconnector.py
Labels: enhancement
